// This file is generated by FlutterFire CLI.
// Run: flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
// Replace every placeholder below with your real Firebase project values.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // ── Replace these with your real values after running `flutterfire configure` ──

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtMoYYKv7WKYOXkJAPvSz1Cexk1RSM9QU',
    appId: '1:570787286259:web:7bc31c433c501063a57b86',
    messagingSenderId: '570787286259',
    projectId: 'wash-ledgar',
    authDomain: 'wash-ledgar.firebaseapp.com',
    storageBucket: 'wash-ledgar.firebasestorage.app',
    measurementId: 'G-2MZRWM8WV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE24jZUTPPA0_npUe8SlSGgfKNi_Hm1Vk',
    appId: '1:570787286259:android:fecbe479b0ec612da57b86',
    messagingSenderId: '570787286259',
    projectId: 'wash-ledgar',
    storageBucket: 'wash-ledgar.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_PROJECT_ID.appspot.com',
    iosBundleId: 'com.washlog.app',
  );
}
